const boatsData = [
    {
        "id": "0001",
        "name": "Cosma",
        "availability": "",
        "capacity": 4,
        "captain": "y",
        "pricePerDay": 200,
        "length": "10.4",
        "model": "Bavaria Cruiser 46",
        "description": "This is a luxury yacht designed for ocean adventurers. The vessel features a rugged hull and can navigate challenging waters in various conditions. It comes with comfortable staterooms, plenty of deck space, and modern amenities throughout. Its distinctive appearance and smooth ride make it a popular choice among experienced boaters looking for both comfort and capability on the open seas.",
        "location": "Split",
        "year": 2008,
        "image": "0001.jpg"
    },
    {
        "id": "0002",
        "name": "Queen",
        "availability": "",
        "capacity": 3,
        "captain": "n",
        "pricePerDay": 150,
        "length": "6.4",
        "model": "SeaBreeze 285 Cruiser",
        "description": "This is a luxury yacht designed for ocean adventurers. The vessel features a rugged hull and can navigate challenging waters in various conditions. It comes with comfortable staterooms, plenty of deck space, and modern amenities throughout. Its distinctive appearance and smooth ride make it a popular choice among experienced boaters looking for both comfort and capability on the open seas.",
        "location": "Zadar",
        "year": 2005,
        "image": "0002.jpg"
    },
    {
        "id": "0003",
        "name": "Jelena",
        "availability": "",
        "capacity": 4,
        "captain": "n",
        "pricePerDay": 300,
        "length": "11",
        "model": "WaveRunner Elite X42",
        "description": "This is a luxury yacht designed for ocean adventurers. The vessel features a rugged hull and can navigate challenging waters in various conditions. It comes with comfortable staterooms, plenty of deck space, and modern amenities throughout. Its distinctive appearance and smooth ride make it a popular choice among experienced boaters looking for both comfort and capability on the open seas.",
        "location": "Šibenik",
        "year": 2020,
        "image": "0003.jpg"
    },
    {
        "id": "0004",
        "name": "Mira",
        "availability": "",
        "capacity": 6,
        "captain": "y",
        "pricePerDay": 500,
        "length": "16",
        "model": "NorthStar Navigator 330",
        "description": "This is a luxury yacht designed for ocean adventurers. The vessel features a rugged hull and can navigate challenging waters in various conditions. It comes with comfortable staterooms, plenty of deck space, and modern amenities throughout. Its distinctive appearance and smooth ride make it a popular choice among experienced boaters looking for both comfort and capability on the open seas.",
        "location": "Primošten",
        "year": 2017,
        "image": "0004.jpg"
    },
    {
        "id": "0005",
        "name": "Mediteran",
        "availability": "",
        "capacity": 4,
        "captain": "y",
        "pricePerDay": 250,
        "length": "11",
        "model": "AquaVista Sport 225",
        "description": "This is a luxury yacht designed for ocean adventurers. The vessel features a rugged hull and can navigate challenging waters in various conditions. It comes with comfortable staterooms, plenty of deck space, and modern amenities throughout. Its distinctive appearance and smooth ride make it a popular choice among experienced boaters looking for both comfort and capability on the open seas.",
        "location": "Split",
        "year": 2014,
        "image": "0005.jpg"
    },
    {
        "id": "0006",
        "name": "Kaštelanka",
        "availability": "",
        "capacity": 5,
        "captain": "y",
        "pricePerDay": 300,
        "length": "13",
        "model": "CoastalCraft Legacy 38",
        "description": "This is a luxury yacht designed for ocean adventurers. The vessel features a rugged hull and can navigate challenging waters in various conditions. It comes with comfortable staterooms, plenty of deck space, and modern amenities throughout. Its distinctive appearance and smooth ride make it a popular choice among experienced boaters looking for both comfort and capability on the open seas.",
        "location": "Trogir",
        "year": 2018,
        "image": "0006.jpg"
    },
    {
        "id": "0007",
        "name": "Majesty",
        "availability": "",
        "capacity": 5,
        "captain": "n",
        "pricePerDay": 430,
        "length": "14.2",
        "model": "MarineMaster Voyager 295",
        "description": "This is a luxury yacht designed for ocean adventurers. The vessel features a rugged hull and can navigate challenging waters in various conditions. It comes with comfortable staterooms, plenty of deck space, and modern amenities throughout. Its distinctive appearance and smooth ride make it a popular choice among experienced boaters looking for both comfort and capability on the open seas.",
        "location": "Hvar",
        "year": 2019,
        "image": "0007.jpg"
    },
    {
        "id": "0008",
        "name": "Griselda",
        "availability": "",
        "capacity": 3,
        "captain": "n",
        "pricePerDay": 190,
        "length": "7",
        "model": "OceanPro Expedition 420",
        "description": "This is a luxury yacht designed for ocean adventurers. The vessel features a rugged hull and can navigate challenging waters in various conditions. It comes with comfortable staterooms, plenty of deck space, and modern amenities throughout. Its distinctive appearance and smooth ride make it a popular choice among experienced boaters looking for both comfort and capability on the open seas.",
        "location": "Split",
        "year": 2010,
        "image": "0008.jpg"
    },
    {
        "id": "0009",
        "name": "Marjan",
        "availability": "",
        "capacity": 3,
        "captain": "y",
        "pricePerDay": 140,
        "length": "7.5",
        "model": "BlueFin Discovery 265",
        "description": "This is a luxury yacht designed for ocean adventurers. The vessel features a rugged hull and can navigate challenging waters in various conditions. It comes with comfortable staterooms, plenty of deck space, and modern amenities throughout. Its distinctive appearance and smooth ride make it a popular choice among experienced boaters looking for both comfort and capability on the open seas.",
        "location": "Zadar",
        "year": 2009,
        "image": "0009.jpg"
    }
];